[tool.poetry]
name = "aws-s3-demo"
version = "0.1.0"
description = ""
authors = ["Yurii Mironov <yuriymironov96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.28.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
